"""added end date from subs model

Revision ID: 77db0bdb2e71
Revises: 8dbe34bb5986
Create Date: 2025-05-29 00:10:44.970194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77db0bdb2e71'
down_revision: Union[str, None] = '8dbe34bb5986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.drop_column('subscriptions', 'end_date')
    # ### end Alembic commands ###
