"""removed end date from subs model

Revision ID: 8dbe34bb5986
Revises: 27bee7e1d9eb
Create Date: 2025-05-28 23:15:46.841954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dbe34bb5986'
down_revision: Union[str, None] = '27bee7e1d9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.drop_column('subscriptions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
